--- #YAML:1.0
name:                Kvasir-Writer-XML
version:             0.01
abstract:            Store Kvasir engine declarations as XML
license:             MIT
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Kvasir:                        0.05
    Scalar::Util:                  0
    Test::Exception:               0
    Test::More:                    0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Claes Jakobsson <claesjac@cpan.org>
